# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-30 08:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cell', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Scoreboard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Scoreboard', max_length=100)),
                ('theme', models.CharField(default='default', max_length=20)),
                ('num_teams', models.IntegerField(default=0)),
                ('num_rounds', models.IntegerField(default=0)),
                ('teams', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('board', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('history', picklefield.fields.PickledObjectField(default=[], editable=False)),
                ('changed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='GainLossAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.Action')),
                ('points', models.IntegerField(default=0)),
                ('animation_type', models.CharField(choices=[('gain', 'gain'), ('loss', 'loss'), ('null', 'null')], max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('board.action',),
        ),
        migrations.AddField(
            model_name='action',
            name='polymorphic_ctype',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polymorphic_board.action_set+', to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='action',
            name='scoreboard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Scoreboard'),
        ),
        migrations.CreateModel(
            name='PointsChangeAction',
            fields=[
                ('gainlossaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.GainLossAction')),
                ('gl_animation', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('board.gainlossaction',),
        ),
        migrations.CreateModel(
            name='QuestionAction',
            fields=[
                ('pointschangeaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.PointsChangeAction')),
                ('scores', picklefield.fields.PickledObjectField(default=[], editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('board.pointschangeaction',),
        ),
    ]
