# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-21 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_manager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Manager',
        ),
        migrations.AddField(
            model_name='board',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
