# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 09:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_tempbool'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tempbool',
            name='board',
        ),
        migrations.DeleteModel(
            name='TempBool',
        ),
    ]
