# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-22 10:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0007_changedbool_winbool'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempBool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perform', models.BooleanField(default=False)),
                ('team', models.PositiveIntegerField()),
                ('points', models.IntegerField()),
                ('type', models.CharField(choices=[('changed', 'changed'), ('win', 'win'), ('points', 'points')], default='changed', max_length=9)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
            ],
        ),
        migrations.RemoveField(
            model_name='changedbool',
            name='board',
        ),
        migrations.RemoveField(
            model_name='winbool',
            name='board',
        ),
        migrations.DeleteModel(
            name='ChangedBool',
        ),
        migrations.DeleteModel(
            name='WinBool',
        ),
    ]
