# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 08:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0011_remove_board_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='num_rounds',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='board',
            name='num_teams',
            field=models.IntegerField(default=0),
        ),
    ]
