# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 08:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0012_auto_20171223_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='teams',
            field=models.CharField(default='Rounds|', max_length=300),
        ),
    ]
