# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0013_board_teams'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='title',
            field=models.CharField(default='Scoreboard', max_length=100),
        ),
    ]
