# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 11:23
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0015_board_arr_json'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='arr_json',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
