# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 11:29
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0016_auto_20171223_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='arr_json',
            field=picklefield.fields.PickledObjectField(editable=False, null=True),
        ),
    ]
