# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 13:18
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0017_auto_20171223_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='arr_json',
            field=picklefield.fields.PickledObjectField(default=0, editable=False),
        ),
    ]
