# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-23 13:30
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0018_auto_20171223_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='arr_json',
        ),
        migrations.AlterField(
            model_name='board',
            name='teams',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
    ]
