# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 16:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0020_board_board'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Board',
            new_name='Scoreboard',
        ),
    ]
