# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-26 17:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0021_auto_20171226_2206'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
