# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 05:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0022_scoreboard_changed'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='theme',
            field=models.CharField(default='default', max_length=20),
        ),
    ]
