# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0024_auto_20171227_1737'),
    ]

    operations = [
        migrations.CreateModel(
            name='GainLossAction',
            fields=[
                ('action_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.Action')),
                ('points', models.IntegerField(default=0)),
                ('type', models.CharField(max_length=5)),
            ],
            options={
                'abstract': False,
            },
            bases=('board.action',),
        ),
    ]
