# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-27 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0025_gainlossaction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gainlossaction',
            old_name='type',
            new_name='animation_type',
        ),
    ]
