# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0026_auto_20171227_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsChangeAction',
            fields=[
                ('gainlossaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.GainLossAction')),
            ],
            options={
                'abstract': False,
            },
            bases=('board.gainlossaction',),
        ),
        migrations.AlterField(
            model_name='gainlossaction',
            name='animation_type',
            field=models.CharField(choices=[('gain', 'gain'), ('loss', 'loss'), ('null', 'null')], max_length=5),
        ),
    ]
