# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 04:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0027_auto_20171228_0930'),
    ]

    operations = [
        migrations.AddField(
            model_name='pointschangeaction',
            name='gl_animation',
            field=models.BooleanField(default=False),
        ),
    ]
