# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-28 07:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0028_pointschangeaction_gl_animation'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionAction',
            fields=[
                ('pointschangeaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='board.PointsChangeAction')),
                ('scores', picklefield.fields.PickledObjectField(default=[], editable=False)),
            ],
            options={
                'abstract': False,
            },
            bases=('board.pointschangeaction',),
        ),
    ]
