# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 13:55
from __future__ import unicode_literals

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0030_auto_20171229_1146'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={},
        ),
        migrations.AlterModelManagers(
            name='action',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='gainlossaction',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='pointschangeaction',
            managers=[
            ],
        ),
        migrations.AlterModelManagers(
            name='questionaction',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='questionaction',
            name='scores',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='board',
            field=jsonfield.fields.JSONField(default=[]),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='teams',
            field=jsonfield.fields.JSONField(default=[]),
        ),
    ]
