# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 13:58
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0031_auto_20171229_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionaction',
            name='scores',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='board',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
        migrations.AlterField(
            model_name='scoreboard',
            name='teams',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
    ]
