# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2017-12-29 15:03
from __future__ import unicode_literals

from django.db import migrations
import picklefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0032_auto_20171229_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoreboard',
            name='history',
            field=picklefield.fields.PickledObjectField(default=[], editable=False),
        ),
    ]
